version: '3'

services:

  db:
    image: mysql:5.7
    ports:
      - 3327:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      context: .
      dockerfile: dockerfiles/app.dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=${IP_ADDRESS}
    volumes:
      - .:/var/www
      
  web:
    depends_on:
      - app
    build: 
      context: .
      dockerfile: dockerfiles/web.dockerfile
    ports:
      - 8020:80
    volumes:
      - .:/var/www
    restart: always

volumes:
  db_data: